### ISSUE TITLE
IOS fling issue

### ISSUE THREAD

**Issue by pimkle** [LeEnno/stickyHeaders#5]
On IOS, if user scroll view with a fling gesture, the header won't stick until scroll stops. How to achieve the effect that the header would sticky right on the header scroll to top, no matter it's in a fling? (fling: quick scroll on ios)

**Comment by LeEnno** [comment]
thx for your report. you may have a look now, should be working fine.

**Comment by pimkle** [comment]
It IS working on safari.Thank you!
